name: First Workflow
on: 
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'
jobs:
  backup:
    uses: ./.github/workflows/firebase.yml
    with:
      USE_SHORT_SHA_TAG: true
    secrets: inherit
  first-job:
    needs: backup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello World"
